@backend_HostAddress = http://localhost:5147

# GET {{backend_HostAddress}}/api/employee/

# POST {{backend_HostAddress}}/api/employee
# Accept: application/json
# Content-Type: application/json

# {
#     "Name": "Guru",
#     "Education": "Phd",
#     "PhoneNumber": 8822328321
# }

# PUT {{backend_HostAddress}}/api/employee/5
# Accept: application/json
# Content-Type: application/json

# {   
#     "Name": "Naresh",
#     "Education": "Degree",
#     "PhoneNumber": 98474309802
# } 

# DELETE {{backend_HostAddress}}/api/employee/4
# Accept: application/json
# Content-Type: application/json

# GET {{backend_HostAddress}}/api/user

# POST {{backend_HostAddress}}/api/user
# Accept: application/json
# Content-Type: application/json

# {
#     "username": "Shiva",
#     "comments": ["newlogin","resubmitted"]
# }

# PUT {{backend_HostAddress}}/api/user/9
# Accept: application/json
# Content-Type: application/json

# {   
#     "username": "Shiva",
#     "comments": ["newlogin","resubmitted"]
# }

# DELETE {{backend_HostAddress}}/api/user/10
# Accept: application/json
# Content-Type: application/json

###
